apiVersion: v1
kind: Service
metadata:
  name: coworking-space
spec:
  selector:
    service: coworking-space
  ports:
  - name: "8888"
    protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-space
  labels:
    name: coworking-space
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking-space
  template:
    metadata:
      labels:
        service: coworking-space
    spec:
      containers:
      - name: coworking-space
        image: 033660244995.dkr.ecr.us-east-1.amazonaws.com/coworking-space:8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 8888
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 8888
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-env
              key: APP_PORT
      restartPolicy: Always
