kind: PersistentVolume
apiVersion: v1
metadata:
  name: coworking-db-pv
  labels:
    type: local
    app: coworking-db
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: coworking-db-pvc
  labels:
    app: coworking-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi